[game]
hostname = "[MRP][RU]Victoria - оплот истории вселенной"
desc = "Сервер со средними требованиями к Роле-плею.\nРазвивающийся проект в процессе разработки.\nПервоначально ориентирован на создание и поддержание атмосферы и проработанной вселенной для отыгровки."
map_pool = "VictoriaDefaultMapPool"
maxplayers = 120
soft_max_players = 100
map_rotation = true
role_timers = false

[server]
rules_file = "VictoriaRuleset"

[viewport]
maximum_width = 29

[game.panic_bunker]
enabled = false
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = false
disable_with_admins = false

[rules]
time = 90

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
