- type: entity
  id: BaseStationGoalVictoria
  abstract: true
  components:
    - type: StationGoal
      goals:
      - AccumulationElectricity
      - ProtectiveField
      - ExpansionDormitories
      - TrainingArea
      - ColonySupply
      - CombinedMedications
      - StudyingAnomalies
      - Singularity
      - SolarPanels
      - Artifacts
      - Bank
      - Zoo
      - MiningOutpost
      - Tesla
      - SecurityTraining
      - ShuttleMed
      - ShuttleSec
      - ShuttleRnd
      - ShuttleSrv
      - ShuttleEmergency
      - Theatre
      - CellAI
      - Botany
      - Bunker
      - Survive